services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
