include:
  - backend-include.yaml
services:
  frontend:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
